export const routes = {
  home: "/",
  blogs: "/blogs",
  chatbot: "/chatbot",
  login: "/login",
  register: "/register",
  passwordReset: "/password-reset",
  admin: "/admin",
  adminUsers: "/admin/users",
  adminDoctors: "/admin/doctors",
  adminSymptomChecks: "/admin/symptom-checks",
  adminAiFlags: "/admin/ai-flags",
  adminContent: "/admin/content",
  adminContentNew: "/admin/content/new",
  adminConsultations: "/admin/consultations",
  adminReports: "/admin/reports",
  adminAuditLogs: "/admin/audit-logs",
  adminNotifications: "/admin/notifications",
  adminTesting: "/admin/testing",
  adminSettings: "/admin/settings",
  adminMentalHealthResources: "/admin/settings/mental-health-resources",
  adminHealthResources: "/admin/settings/health-resources",
  unauthorized: "/unauthorized"
} as const;
